config/routes.rb
Rails.application.routes.draw do
  root 'bots#index'
  resources :bots
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot.rb
class Bot < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  before_action :set_bot, only: [:show, :edit, :update, :destroy]

  # GET /bots
  # GET /bots.json
  def index
    @bots = Bot.all
  end

  # GET /bots/1
  # GET /bots/1.json
  def show
  end

  # GET /bots/new
  def new
    @bot = Bot.new
  end

  # GET /bots/1/edit
  def edit
  end

  # POST /bots
  # POST /bots.json
  def create
    @bot = Bot.new(bot_params)

    respond_to do |format|
      if @bot.save
        SlackPostJob.perform_later(@bot.requirement)
        format.html { redirect_to @bot, notice: 'Bot was successfully created.' }
        format.json { render :show, status: :created, location: @bot }
      else
        format.html { render :new }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bots/1
  # PATCH/PUT /bots/1.json
  def update
    respond_to do |format|
      if @bot.update(bot_params)
        format.html { redirect_to @bot, notice: 'Bot was successfully updated.' }
        format.json { render :show, status: :ok, location: @bot }
      else
        format.html { render :edit }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bots/1
  # DELETE /bots/1.json
  def destroy
    @bot.destroy
    respond_to do |format|
      format.html { redirect_to bots_url, notice: 'Bot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bot
      @bot = Bot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bot_params
      params.require(:bot).permit(:requirement)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bots/_form.html.erb
<%= form_with(model: bot, local: true) do |form| %>
  <% if bot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bot.errors.count, "error") %> prohibited this bot from being saved:</h2>

      <ul>
      <% bot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :requirement %>
    <%= form.text_area :requirement %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bots/edit.html.erb
<h1>Editing Bot</h1>

<%= render 'form', bot: @bot %>

<%= link_to 'Show', @bot %> |
<%= link_to 'Back', bots_path %>

app/views/bots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bots</h1>

<table>
  <thead>
    <tr>
      <th>Requirement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bots.each do |bot| %>
      <tr>
        <td><%= bot.requirement %></td>
        <td><%= link_to 'Show', bot %></td>
        <td><%= link_to 'Edit', edit_bot_path(bot) %></td>
        <td><%= link_to 'Destroy', bot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bot', new_bot_path %>

app/views/bots/new.html.erb
<h1>New Bot</h1>

<%= render 'form', bot: @bot %>

<%= link_to 'Back', bots_path %>

app/views/bots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requirement:</strong>
  <%= @bot.requirement %>
</p>

<%= link_to 'Edit', edit_bot_path(@bot) %> |
<%= link_to 'Back', bots_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiveSlackBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>